easy_admin:
    site_name: 'ACME Megacorp.'
    entities:
        Article:
            class : App\Entity\Article
        User:
            class: App\Entity\User
            # Notre controller spécifique
            controller: App\Controller\UserAdminController
            form:
                fields:
                    # Fomulaire de création / modification d'un utilisateur
                    - { property: 'email'}
                    # Ici on retrouve notre propriété plainPassword pour la modification du mot de passe 
                    - { property: 'password', type: 'password'}
                    - { property: 'lastName', label: 'FirstName'}
                    - { property: 'firstName', label: 'FirstName'}
                    - { property: 'avatarImage', label: 'Avatar'}
    design:
        menu:
            - { entity:  'User', label: 'Utilisateurs', default: true }              
            - { entity:  'Article', label: 'Articles' }       
            - { label: 'Déconnexion', route: 'app_logout', icon: ''}       
